第３回課題の提出
mai-ishikawa02/RaiseTech pull request #2
Opened 2023-05-09 15:07 UTC by mai-ishikawa02

## 第3回課題を追加しました。
- APサーバーについて
- DBサーバーについて
- 構成管理ツール
- 今回の学び

2023-05-09 16:21 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応ください！

2023-05-09 16:21 UTC, MasatoshiMizumoto commented on lecture03.md
画像リンクが全てリンク切れ判定されているので、書き方を確認してみてください！
ファイルの配置方法はOKですので、Markdown記法の確認と対応になります！

2023-05-10 13:07 UTC, mai-ishikawa02 commented
第3回課題を修正しました。
相対パスで記載してみました。

2023-05-10 13:30 UTC, mai-ishikawa02 commented
第3回課題を修正しました。
相対パスで入力してみました。

2023-05-10 14:09 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-05-17 11:52 UTC, merged